name: Demo-1

on:
  push:

jobs:
  hello-world:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Print a Message
        run: echo "Hello from GHA"
